<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sourcepub</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^.*\bfunction\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>SourcePub</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|else|elif|for|include|locals|globals|print|load|cload|def|true|false|return)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([a-zA-Z_?.$][\w?.$]*)\.([a-zA-Z_?.$][\w?.$]*)\s*(=)\s*(lambda)\s*(\()(.*?)(\))</string>
			<key>name</key>
			<string>lambda</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([a-zA-Z_?$][\w?$]*)\s*(=)\s*(lambda)\s*(\()(.*?)(\))</string>
			<key>name</key>
			<string>lambda</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z_?.$][\w?.$]*)\s*:\s*\b(lambda)?\s*(\()(.*?)(\))</string>
			<key>name</key>
			<string>lambda</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(rfn3|append|bind|bitwise_and|bitwise_or|ceil|cmp|contains|copy|days_from_now|decorate|default|dump_env|enable_wss|enumerate|exp|floor|fork|format_float|format_int|hidden_escape|html_escape|import|int|internal_dump|isnull|items|join|json2pub|json_escape|keys|len|list|log|logwarn|lookup|map|match|now|okws_version_int|okws_version_str|pop_front|pow|rand|randsel|range|replace|reverse|round|search|sha1|shotgun|shuffle|sleep|sort|splice|split|sqrt|str|strip|strptime|substr|tag_escape|time_format|time_from_now|tolower|toupper|type|unbind|url_escape|url_unescape|utf8_fix|values|version_int|version_str|warn|warn_trace|wss_filter|bit_set|br_to_newline|commaify|get_exp_group|json_uber_filter|json_uber_lite|money|newline_to_br|pluralize|regex_replace|remove_brackets_amp|sfs_hash|strip_html|strip_html_dutil|strip_newline|tidy|unescape_html_entities|utf8_fix)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(//).*?($\n?|(?=\?&gt;))</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|\-|&lt;|&gt;|\|\||&amp;&amp;|=</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pub</string>
	<key>uuid</key>
	<string>009FA760-AB97-11E1-AFA6-0800200C9A66</string>
</dict>
</plist>